-- Create a simple todos table for testing
create table if not exists todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (optional, but good practice)
alter table todos enable row level security;

-- Create a policy that allows anyone to read/write (for development only)
-- WARNING: In production, you should restrict this to authenticated users
create policy "Public Access" on todos for all using (true);
