-- 1. Create a table for public profiles
-- This table will store user data that is safe to be publicly readable.
-- We are also enabling Row Level Security (RLS).
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  website text,

  constraint full_name_length check (char_length(full_name) >= 3)
);

alter table profiles
  enable row level security;

-- Policies for profiles table
-- 1. Users can view their own profile.
create policy "Users can view their own profile." on profiles
  for select using (auth.uid() = id);

-- 2. Users can insert their own profile.
create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

-- 3. Users can update their own profile.
create policy "Users can update their own profile." on profiles
  for update using (auth.uid() = id);


-- 2. Create a 'clients' table
-- This table will store the client initials managed by each user.
create table clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  initials text not null,
  user_id uuid references auth.users not null
);

alter table clients
  enable row level security;

-- Policies for clients table
-- 1. Users can view their own clients.
create policy "Users can view their own clients." on clients
  for select using (auth.uid() = user_id);

-- 2. Users can insert clients for themselves.
create policy "Users can insert their own clients." on clients
  for insert with check (auth.uid() = user_id);

-- 3. Users can update their own clients.
create policy "Users can update their own clients." on clients
  for update using (auth.uid() = user_id);

-- 4. Users can delete their own clients.
create policy "Users can delete their own clients." on clients
  for delete using (auth.uid() = user_id);


-- 3. Create a 'case_plans' table
-- This table will store the generated case plans for each client.
create table case_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  content text not null,
  urgency text,
  status text default 'Not Started' not null, -- e.g., 'Not Started', 'In Progress', 'Completed'
  client_id bigint references clients not null,
  user_id uuid references auth.users not null
);

alter table case_plans
  enable row level security;

-- Policies for case_plans table
-- 1. Users can view plans for their own clients.
create policy "Users can view their own case plans." on case_plans
  for select using (auth.uid() = user_id);

-- 2. Users can insert plans for their own clients.
create policy "Users can insert their own case plans." on case_plans
  for insert with check (auth.uid() = user_id);

-- 3. Users can update their own plans.
create policy "Users can update their own case plans." on case_plans
  for update using (auth.uid() = user_id);

-- 4. Users can delete their own plans.
create policy "Users can delete their own case plans." on case_plans
  for delete using (auth.uid() = user_id);


-- 4. Set up a trigger to automatically create a profile when a new user signs up.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
