-- Session logging table for tracking user sign-ins and sign-outs
-- This allows admins to monitor user activity
-- PII is pseudonymized: email is stored as a SHA-256 hash, IP is not stored

CREATE TABLE IF NOT EXISTS session_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  email_hash text,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('sign_in', 'sign_out', 'token_refresh')),
  metadata jsonb DEFAULT '{}'::jsonb
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_session_logs_user_id ON session_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_email_hash ON session_logs(email_hash);
CREATE INDEX IF NOT EXISTS idx_session_logs_created_at ON session_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_logs_action ON session_logs(action);

-- Enable RLS
ALTER TABLE session_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own session logs by user_id
CREATE POLICY "Users can view their own session logs"
  ON session_logs
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Authenticated users can insert logs, but only for themselves
CREATE POLICY "Authenticated users can log sessions"
  ON session_logs
  FOR INSERT
  WITH CHECK (
    (auth.role() = 'authenticated' AND user_id = auth.uid())
    OR auth.role() = 'service_role'
  );

-- Create a SECURITY DEFINER function for admin access to all session logs
-- This bypasses RLS safely and is only callable via RPC
CREATE OR REPLACE FUNCTION get_admin_session_logs(row_limit int DEFAULT 100)
RETURNS TABLE (
  id bigint,
  created_at timestamp with time zone,
  email_hash text,
  user_id uuid,
  action text,
  metadata jsonb
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT sl.id, sl.created_at, sl.email_hash, sl.user_id, sl.action, sl.metadata
  FROM session_logs sl
  ORDER BY sl.created_at DESC
  LIMIT row_limit;
$$;

-- Retention: function to clean up old session logs
-- Call this on a schedule (e.g., pg_cron) with desired retention days
CREATE OR REPLACE FUNCTION cleanup_old_session_logs(retention_days int DEFAULT 90)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count int;
BEGIN
  DELETE FROM session_logs
  WHERE created_at < now() - (retention_days || ' days')::interval;
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

COMMENT ON TABLE session_logs IS 'Tracks user sign-in and sign-out events for audit purposes. Email stored as hash for privacy. Default retention: 90 days.';
