-- Session logging table for tracking user sign-ins and sign-outs
-- This allows admins to monitor user activity

CREATE TABLE IF NOT EXISTS session_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  user_email text NOT NULL,
  user_id uuid REFERENCES auth.users,
  action text NOT NULL CHECK (action IN ('sign_in', 'sign_out', 'token_refresh')),
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_session_logs_user_email ON session_logs(user_email);
CREATE INDEX IF NOT EXISTS idx_session_logs_created_at ON session_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_logs_action ON session_logs(action);

-- Enable RLS
ALTER TABLE session_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Only admins can view all session logs
-- Regular users can only see their own logs
CREATE POLICY "Users can view their own session logs"
  ON session_logs
  FOR SELECT
  USING (auth.email() = user_email);

-- Policy: Anyone can insert (for logging purposes)
-- The service role or authenticated users can log sessions
CREATE POLICY "Authenticated users can log sessions"
  ON session_logs
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Create a view for admin to see all sessions
CREATE OR REPLACE VIEW admin_session_logs AS
SELECT 
  sl.*,
  COALESCE(p.full_name, sl.user_email) as display_name
FROM session_logs sl
LEFT JOIN profiles p ON sl.user_id = p.id
ORDER BY sl.created_at DESC;

-- Grant access to the view
GRANT SELECT ON admin_session_logs TO authenticated;

COMMENT ON TABLE session_logs IS 'Tracks user sign-in and sign-out events for audit purposes';
